# Generated by Django 3.2 on 2022-01-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceru', '0002_alter_guest_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
