# Generated by Django 3.2 on 2022-01-30 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ceru', '0003_rename_bookings_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='username',
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to=settings.AUTH_USER_MODEL),
        ),
    ]
