# Generated by Django 3.2 on 2022-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceru', '0005_auto_20220130_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
