# Generated by Django 3.2 on 2022-02-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceru', '0011_auto_20220223_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
